# Generated by Django 6.0.1 on 2026-01-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=100)),
                ("year_start", models.IntegerField()),
                ("year_end", models.IntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
